[package]
name = "tchatchers_front"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
gloo-console = "0.2.3"
gloo-net = "0.2.6"
gloo-timers = "0.2.6"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
web-sys = { version = "0.3.61", features = ["HtmlDocument", "FileReader"] }
yew = { version = "0.20.0", features = ["csr"] }
yew-agent = "0.2.0"
yew-router = "0.17.0"
tchatchers_core = { path = "../tchatchers_core", features = ["front"] }
chrono = { version = "0.4.24", features = ["serde"] }
js-sys = "0.3.61"
reqwest-wasm = "0.11.16"
uuid = { version = "1.3.0", features = ["v4"] }
validator = "0.16.0"
chrono-tz = "0.8.2"
async-recursion = "1.0.4"
